version: '3.8'

networks:
  lux-network:
    name: lux-network

volumes:
  pgdata:

services:
  lux-postgres:
    image: postgres:15-alpine
    hostname: lux-postgres
    container_name: lux-postgres
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - lux-network

  lux-app:
    build: .
    image: lux-app
    hostname: lux-app
    container_name: lux-app
    restart: on-failure
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - lux-network
    depends_on:
      - lux-postgres
    links:
      - lux-postgres
